#if NIGHTDRIVE_DEVELOPMENT_TOOLS
  import AppKit
  import Foundation

  @MainActor
  enum DevelopmentSyncTools {
    private static let corruptLedgerContents = Data(
      "not json — generated by Develop ▸ Sync ▸ Corrupt Sync Ledger".utf8)

    static func resetLedger(for device: IpodDevice, app: AppState) {
      guard
        DevelopmentSafety.requireFakeVolume(
          device.volumeURL, action: "reset the sync ledger")
      else { return }
      guard let libraryFolder = app.library.folderURL else {
        DevelopmentAlert.show(
          title: "No library folder",
          message: "The sync ledger lives in the library folder. Choose one first.")
        return
      }
      guard let databaseID = device.databaseID else {
        DevelopmentAlert.show(
          title: "This iPod has no database ID",
          message: "There is no ledger section to reset until it has been read once.")
        return
      }
      guard
        DevelopmentAlert.confirm(
          title: "Reset the sync ledger for \(app.displayName(for: device))?",
          message: """
            The next sync will treat every song as newly paired. Nothing is \
            copied or deleted by this; only Nightdrive's record of what is \
            already on the iPod goes away.
            """,
          proceedTitle: "Reset")
      else { return }
      do {
        try SyncLedgerStore.replaceEntries([], for: databaseID, libraryFolder: libraryFolder)
        try SyncLedgerStore.replacePlaylistLinks(
          [], for: databaseID, libraryFolder: libraryFolder)
      } catch {
        DevelopmentAlert.report(error, doing: "reset the sync ledger")
        return
      }
      Task { await app.deviceManager.reload(device) }
    }

    static func corruptLedger(for device: IpodDevice, app: AppState) async {
      guard
        DevelopmentSafety.requireFakeVolume(
          device.volumeURL, action: "corrupt the sync ledger")
      else { return }
      guard !app.isDeviceOperationActive else {
        DevelopmentAlert.show(
          title: "A device operation is in progress",
          message: "Wait for the current sync or repair to finish, then try again.")
        return
      }
      guard let libraryFolder = app.library.folderURL else {
        DevelopmentAlert.show(
          title: "No library folder",
          message: "The sync ledger lives in the library folder. Choose one first.")
        return
      }
      guard isDisposableDevelopmentLibrary(libraryFolder) else {
        DevelopmentAlert.show(
          title: "Use a development library first",
          message: """
            Corrupting a sync ledger destroys its link history, so this tool only works with the \
            disposable libraries created from Develop ▸ Library.
            """)
        return
      }
      let ledgerURL = SyncLedgerStore.url(for: libraryFolder)
      guard
        DevelopmentAlert.confirm(
          title: "Corrupt the demo library's sync ledger?",
          message: """
            \(ledgerURL.path) will be replaced with invalid JSON. Start a sync afterward to show \
            the recovery dialog and test reopening it from the head-unit display.
            """,
          proceedTitle: "Corrupt")
      else { return }

      await app.flushSyncSettingsWrites()
      do {
        let workflowLock = try await ScopedAdvisoryLock.acquire(
          for: libraryFolder, namespace: .libraryWorkflow)
        defer { workflowLock.unlock() }
        let ledgerLock = try await ScopedAdvisoryLock.acquire(
          for: libraryFolder, namespace: .library)
        defer { ledgerLock.unlock() }
        guard !app.isDeviceOperationActive,
          app.library.folderURL?.standardizedFileURL == libraryFolder.standardizedFileURL
        else { return }
        try corruptLedgerFile(libraryFolder: libraryFolder)
      } catch {
        DevelopmentAlert.report(error, doing: "corrupt the sync ledger")
      }
    }

    static func isDisposableDevelopmentLibrary(
      _ url: URL, appDataDirectory: URL = NightdriveAppData.defaultDirectoryURL
    ) -> Bool {
      let folder = url.resolvingSymlinksInPath().standardizedFileURL
      let root = appDataDirectory.resolvingSymlinksInPath().standardizedFileURL
      return folder == root.appendingPathComponent("DevelopmentLibrary", isDirectory: true)
        || folder == root.appendingPathComponent("DevelopmentMessyLibrary", isDirectory: true)
    }

    static func corruptLedgerFile(libraryFolder: URL) throws {
      try corruptLedgerContents.write(
        to: SyncLedgerStore.url(for: libraryFolder), options: .atomic)
    }

    static func showLedger(app: AppState) {
      guard let libraryFolder = app.library.folderURL else {
        DevelopmentAlert.show(
          title: "No library folder",
          message: "The sync ledger lives in the library folder. Choose one first.")
        return
      }
      let url = SyncLedgerStore.url(for: libraryFolder)
      let text: String
      if let data = try? Data(contentsOf: url),
        let object = try? JSONSerialization.jsonObject(with: data),
        let pretty = try? JSONSerialization.data(
          withJSONObject: object, options: [.prettyPrinted, .sortedKeys]),
        let rendered = String(data: pretty, encoding: .utf8)
      {
        text = "\(url.path)\n\n\(rendered)"
      } else {
        text = "No ledger at \(url.path) yet. It is written by the first sync."
      }
      DevelopmentWindowPresenter.showText("sync-ledger", title: "Sync Ledger", text: text)
    }
  }
#endif
