import Foundation

/// The little-endian shadow database used by third- and fourth-generation
/// iPod shuffles. Its chunk names appear byte-reversed on disk (`bdhs`,
/// `hths`, `rths`, `hphs`, and `lphs`).
enum ModernShuffleDatabaseFile {
  static let headerLength = 64
  static let trackHeaderBaseLength = 20
  static let trackLength = 372
  static let playlistHeaderBaseLength = 20
  static let playlistBaseLength = 44

  private static let maximumItemCount = 100_000

  struct Track: Equatable, Sendable {
    var ipodPath: String
    var startMS: UInt32
    var stopMS: UInt32
    var volumeAdjustment: Int32
    var filetype: UInt32
    var bookmarkMS: UInt32
    var playsWhenShuffling: Bool
    var remembersPlaybackPosition: Bool
    var gaplessAlbum: Bool
    var pregap: UInt32
    var postgap: UInt32
    var sampleCount: UInt32
    var gaplessData: UInt32
    var albumID: UInt32
    var trackNumber: UInt16
    var discNumber: UInt16
    var dbid: UInt64
    var artistID: UInt32
  }

  struct Playlist: Equatable, Sendable {
    var dbid: UInt64
    var type: UInt32
    var trackIndexes: [UInt32]
  }

  struct Snapshot: Equatable, Sendable {
    var tracks: [Track]
    var playlists: [Playlist]
    var tracksWithoutPodcastsOrAudiobooks: UInt32
  }

  static func write(_ database: ITunesDatabase) throws -> Data {
    let snapshot = try snapshot(for: database)
    let trackHeaderLength = try checkedLength(
      base: trackHeaderBaseLength, count: snapshot.tracks.count, stride: 4)
    let trackRecordsLength = try checkedLength(
      base: 0, count: snapshot.tracks.count, stride: trackLength)
    let playlistHeaderOffset = try checkedSum(
      headerLength, trackHeaderLength, trackRecordsLength)

    var playlistRecords: [Data] = []
    playlistRecords.reserveCapacity(snapshot.playlists.count)
    for playlist in snapshot.playlists {
      let totalLength = try checkedLength(
        base: playlistBaseLength, count: playlist.trackIndexes.count, stride: 4)
      var writer = ByteWriter(capacity: totalLength)
      writer.tag("lphs")
      writer.u32(try uint32(totalLength))
      writer.u32(try uint32(playlist.trackIndexes.count))
      writer.u32(try uint32(playlist.trackIndexes.count))
      writer.u64(playlist.dbid)
      writer.u32(playlist.type)
      writer.zero32(4)
      for index in playlist.trackIndexes { writer.u32(index) }
      assert(writer.count == totalLength)
      playlistRecords.append(writer.data)
    }

    let playlistHeaderLength = try checkedLength(
      base: playlistHeaderBaseLength, count: snapshot.playlists.count, stride: 4)
    var totalLength = try checkedSum(playlistHeaderOffset, playlistHeaderLength)
    for record in playlistRecords {
      totalLength = try checkedSum(totalLength, record.count)
    }
    var writer = ByteWriter(capacity: totalLength)
    writer.tag("bdhs")
    writer.u32(0x0200_0003)
    writer.u32(UInt32(headerLength))
    writer.u32(try uint32(snapshot.tracks.count))
    writer.u32(try uint32(snapshot.playlists.count))
    writer.u64(0)
    writer.u8(0)  // no maximum-volume limit
    writer.u8(0)  // VoiceOver files are not generated by Nightdrive
    writer.u16(0)
    // Firmware uses this separate count to exclude spoken-word media from
    // the ordinary song rotation even though those tracks remain in `hths`.
    writer.u32(snapshot.tracksWithoutPodcastsOrAudiobooks)
    writer.u32(UInt32(headerLength))
    writer.u32(try uint32(playlistHeaderOffset))
    writer.zero32(5)
    assert(writer.count == headerLength)

    writer.tag("hths")
    writer.u32(try uint32(trackHeaderLength))
    writer.u32(try uint32(snapshot.tracks.count))
    writer.u64(0)
    var trackOffset = headerLength + trackHeaderLength
    for _ in snapshot.tracks {
      writer.u32(try uint32(trackOffset))
      trackOffset = try checkedSum(trackOffset, trackLength)
    }

    for track in snapshot.tracks {
      writer.tag("rths")
      writer.u32(UInt32(trackLength))
      writer.u32(track.startMS)
      writer.u32(track.stopMS)
      writer.i32(track.volumeAdjustment)
      writer.u32(track.filetype)
      let path = Data(slashPath(track.ipodPath).utf8)
      guard path.count < 256 else {
        throw ITunesDBError.badHeader(
          "shuffle track path exceeds the 255-byte firmware limit")
      }
      writer.bytes(path)
      writer.bytes(Data(count: 256 - path.count))
      writer.u32(track.bookmarkMS)
      writer.u8(track.playsWhenShuffling ? 1 : 0)
      writer.u8(track.remembersPlaybackPosition ? 1 : 0)
      writer.u8(track.gaplessAlbum ? 1 : 0)
      writer.u8(0)
      writer.u32(track.pregap)
      writer.u32(track.postgap)
      writer.u32(track.sampleCount)
      writer.u32(0)
      writer.u32(track.gaplessData)
      writer.u32(0)
      writer.u32(track.albumID)
      writer.u16(track.trackNumber)
      writer.u16(track.discNumber)
      writer.u64(0)
      writer.u64(track.dbid)
      writer.u32(track.artistID)
      writer.zero32(8)
    }
    assert(writer.count == playlistHeaderOffset)

    writer.tag("hphs")
    writer.u32(try uint32(playlistHeaderLength))
    writer.u32(try uint32(snapshot.playlists.count))
    writer.u16(0xFFFF)
    writer.u16(1)
    writer.u16(0xFFFF)
    writer.u16(0)
    var playlistOffset = try checkedSum(playlistHeaderOffset, playlistHeaderLength)
    for record in playlistRecords {
      writer.u32(try uint32(playlistOffset))
      playlistOffset = try checkedSum(playlistOffset, record.count)
    }
    for record in playlistRecords { writer.bytes(record) }
    return writer.data
  }

  static func read(_ data: Data) throws -> Snapshot {
    let reader = ByteReader(data)
    guard reader.count >= headerLength, try reader.tag(0) == "bdhs" else {
      throw ITunesDBError.badHeader("modern shuffle database does not start with bdhs")
    }
    guard try reader.u32(4) == 0x0200_0003,
      try reader.u32(8) == UInt32(headerLength)
    else {
      throw ITunesDBError.badHeader("modern shuffle database header constants are wrong")
    }
    let trackCount = try itemCount(reader.u32(12), named: "track")
    let playlistCount = try itemCount(reader.u32(16), named: "playlist")
    let tracksWithoutPodcastsOrAudiobooks = try reader.u32(32)
    guard tracksWithoutPodcastsOrAudiobooks <= UInt32(trackCount) else {
      throw ITunesDBError.badHeader("modern shuffle ordinary-track count is invalid")
    }
    let trackHeaderOffset = Int(try reader.u32(36))
    let playlistHeaderOffset = Int(try reader.u32(40))
    guard trackHeaderOffset == headerLength, playlistHeaderOffset >= headerLength,
      playlistHeaderOffset < reader.count
    else {
      throw ITunesDBError.badHeader("modern shuffle chunk offsets are invalid")
    }

    let trackHeaderLength = try checkedLength(
      base: trackHeaderBaseLength, count: trackCount, stride: 4)
    guard try reader.tag(trackHeaderOffset) == "hths",
      try reader.u32(trackHeaderOffset + 4) == UInt32(trackHeaderLength),
      try reader.u32(trackHeaderOffset + 8) == UInt32(trackCount)
    else {
      throw ITunesDBError.badHeader("modern shuffle track header is invalid")
    }

    var tracks: [Track] = []
    tracks.reserveCapacity(trackCount)
    var expectedTrackOffset = try checkedSum(trackHeaderOffset, trackHeaderLength)
    for index in 0..<trackCount {
      let offset = Int(try reader.u32(trackHeaderOffset + trackHeaderBaseLength + index * 4))
      guard offset == expectedTrackOffset,
        try checkedSum(offset, trackLength) <= playlistHeaderOffset,
        try reader.tag(offset) == "rths",
        try reader.u32(offset + 4) == UInt32(trackLength)
      else {
        throw ITunesDBError.badHeader("modern shuffle track \(index) has invalid bounds")
      }
      let rawPath = try reader.slice(offset + 24, 256)
      let pathBytes = rawPath.prefix { $0 != 0 }
      guard !pathBytes.isEmpty, let path = String(data: pathBytes, encoding: .utf8) else {
        throw ITunesDBError.badHeader("modern shuffle track \(index) has an invalid path")
      }
      let filetype = try reader.u32(offset + 20)
      guard [UInt32(1), 2, 4].contains(filetype) else {
        throw ITunesDBError.badHeader(
          "modern shuffle track \(index) has unknown file type \(filetype)")
      }
      tracks.append(
        Track(
          ipodPath: colonPath(path), startMS: try reader.u32(offset + 8),
          stopMS: try reader.u32(offset + 12),
          volumeAdjustment: Int32(bitPattern: try reader.u32(offset + 16)),
          filetype: filetype, bookmarkMS: try reader.u32(offset + 280),
          playsWhenShuffling: try reader.u8(offset + 284) != 0,
          remembersPlaybackPosition: try reader.u8(offset + 285) != 0,
          gaplessAlbum: try reader.u8(offset + 286) != 0,
          pregap: try reader.u32(offset + 288), postgap: try reader.u32(offset + 292),
          sampleCount: try reader.u32(offset + 296),
          gaplessData: try reader.u32(offset + 304), albumID: try reader.u32(offset + 312),
          trackNumber: try reader.u16(offset + 316), discNumber: try reader.u16(offset + 318),
          dbid: try reader.u64(offset + 328), artistID: try reader.u32(offset + 336)))
      expectedTrackOffset = try checkedSum(expectedTrackOffset, trackLength)
    }
    guard expectedTrackOffset == playlistHeaderOffset else {
      throw ITunesDBError.badHeader("modern shuffle track chunks do not tile the file")
    }

    let playlistHeaderLength = try checkedLength(
      base: playlistHeaderBaseLength, count: playlistCount, stride: 4)
    guard try reader.tag(playlistHeaderOffset) == "hphs",
      try reader.u32(playlistHeaderOffset + 4) == UInt32(playlistHeaderLength),
      try reader.u32(playlistHeaderOffset + 8) == UInt32(playlistCount)
    else {
      throw ITunesDBError.badHeader("modern shuffle playlist header is invalid")
    }

    var playlists: [Playlist] = []
    playlists.reserveCapacity(playlistCount)
    var expectedPlaylistOffset = try checkedSum(playlistHeaderOffset, playlistHeaderLength)
    for index in 0..<playlistCount {
      let offset = Int(
        try reader.u32(playlistHeaderOffset + playlistHeaderBaseLength + index * 4))
      guard offset == expectedPlaylistOffset, try reader.tag(offset) == "lphs" else {
        throw ITunesDBError.badHeader("modern shuffle playlist \(index) has invalid bounds")
      }
      let memberCount = try itemCount(reader.u32(offset + 8), named: "playlist member")
      let recordLength = try checkedLength(
        base: playlistBaseLength, count: memberCount, stride: 4)
      guard try reader.u32(offset + 4) == UInt32(recordLength),
        try reader.u32(offset + 12) <= UInt32(memberCount),
        try checkedSum(offset, recordLength) <= reader.count
      else {
        throw ITunesDBError.badHeader("modern shuffle playlist \(index) has invalid length")
      }
      let type = try reader.u32(offset + 24)
      guard (1...4).contains(type) else {
        throw ITunesDBError.badHeader("modern shuffle playlist \(index) has invalid type")
      }
      var members: [UInt32] = []
      members.reserveCapacity(memberCount)
      for memberIndex in 0..<memberCount {
        let trackIndex = try reader.u32(offset + playlistBaseLength + memberIndex * 4)
        guard trackIndex < UInt32(trackCount) else {
          throw ITunesDBError.badHeader(
            "modern shuffle playlist \(index) refers to a missing track")
        }
        members.append(trackIndex)
      }
      playlists.append(
        Playlist(dbid: try reader.u64(offset + 16), type: type, trackIndexes: members))
      expectedPlaylistOffset = try checkedSum(expectedPlaylistOffset, recordLength)
    }
    guard expectedPlaylistOffset == reader.count else {
      throw ITunesDBError.badHeader("modern shuffle playlist chunks do not tile the file")
    }
    return Snapshot(
      tracks: tracks, playlists: playlists,
      tracksWithoutPodcastsOrAudiobooks: tracksWithoutPodcastsOrAudiobooks)
  }

  static func matches(_ data: Data, database: ITunesDatabase) -> Bool {
    guard let existing = try? read(data), let intended = try? snapshot(for: database) else {
      return false
    }
    return existing == intended
  }

  static func isModernDatabase(_ data: Data) -> Bool {
    data.count >= 4 && String(bytes: data.prefix(4), encoding: .ascii) == "bdhs"
  }

  private static func snapshot(for database: ITunesDatabase) throws -> Snapshot {
    var albumIDs: [String: UInt32] = [:]
    var artistIDs: [String: UInt32] = [:]
    var tracks: [Track] = []
    var trackIndexByDbid: [UInt64: UInt32] = [:]
    var tracksWithoutPodcastsOrAudiobooks: UInt32 = 0
    tracks.reserveCapacity(database.tracks.count)

    func indexedID(_ value: String?, in values: inout [String: UInt32]) throws -> UInt32 {
      let key = value?.trimmingCharacters(in: .whitespacesAndNewlines) ?? ""
      if let existing = values[key] { return existing }
      let id = try uint32(values.count)
      values[key] = id
      return id
    }

    for source in database.tracks {
      guard let path = source.ipodPath else { continue }
      guard trackIndexByDbid[source.dbid] == nil else {
        throw ITunesDBError.badHeader("duplicate track dbid in shuffle database")
      }
      let slashed = slashPath(path)
      guard Data(slashed.utf8).count < 256 else {
        throw ITunesDBError.badHeader(
          "shuffle track path exceeds the 255-byte firmware limit")
      }
      trackIndexByDbid[source.dbid] = try uint32(tracks.count)
      if source.mediaKind != ITDBMediaKind.podcast.rawValue
        && source.mediaKind != ITDBMediaKind.audiobook.rawValue
      {
        tracksWithoutPodcastsOrAudiobooks += 1
      }
      tracks.append(
        Track(
          ipodPath: colonPath(slashed), startMS: 0, stopMS: source.lengthMS,
          volumeAdjustment: source.volumeAdjustment, filetype: filetype(for: source),
          bookmarkMS: source.bookmarkMS, playsWhenShuffling: !source.skipWhenShuffling,
          remembersPlaybackPosition: source.rememberPlaybackPosition,
          gaplessAlbum: source.gaplessAlbumFlag,
          pregap: source.pregap == 0 ? 0x200 : source.pregap,
          postgap: source.postgap == 0 ? 0x200 : source.postgap,
          sampleCount: UInt32(clamping: source.sampleCount), gaplessData: source.gaplessData,
          albumID: try indexedID(source.album, in: &albumIDs),
          trackNumber: UInt16(clamping: source.trackNumber),
          discNumber: UInt16(clamping: source.discNumber), dbid: source.dbid,
          artistID: try indexedID(source.artist, in: &artistIDs)))
    }

    let allTracks = (0..<tracks.count).map { UInt32($0) }
    var playlists = [Playlist(dbid: 0, type: 1, trackIndexes: allTracks)]
    func append(_ source: ITDBPlaylist, type: UInt32) {
      let members = source.memberDbids.compactMap { trackIndexByDbid[$0] }
      guard !members.isEmpty else { return }
      playlists.append(Playlist(dbid: source.persistentID, type: type, trackIndexes: members))
    }
    for playlist in database.playlists where !playlist.isMaster { append(playlist, type: 2) }
    // A canonical iTunesDB may mirror its standard playlists into the podcast
    // section for older firmware. Only genuinely distinct podcast playlists
    // belong in the modern shuffle's type-3 list. Normalizing matches what
    // ITunesDBWriter emits, so the shuffle database stays idempotent whether
    // the podcast playlist was just synthesized or read back from disk.
    let standardPlaylistIDs = Set(
      [database.masterPlaylistID] + database.playlists.map(\.persistentID))
    for playlist in ITunesDBWriter.normalizedPodcastPlaylists(for: database)
    where !standardPlaylistIDs.contains(playlist.persistentID) {
      append(playlist, type: 3)
    }
    return Snapshot(
      tracks: tracks, playlists: playlists,
      tracksWithoutPodcastsOrAudiobooks: tracksWithoutPodcastsOrAudiobooks)
  }

  private static func filetype(for track: ITDBTrack) -> UInt32 {
    switch track.audioCodec {
    case .mp3: 1
    case .aac: 2
    case .pcm: 4
    case .unknown: 1
    }
  }

  private static func slashPath(_ path: String) -> String {
    let replaced = IpodPath.slashSeparated(path)
    return replaced.hasPrefix("/") ? replaced : "/" + replaced
  }

  private static func colonPath(_ path: String) -> String {
    let replaced = IpodPath.colonSeparated(path)
    return replaced.hasPrefix(":") ? replaced : ":" + replaced
  }

  private static func checkedLength(base: Int, count: Int, stride: Int) throws -> Int {
    let payload = count.multipliedReportingOverflow(by: stride)
    let total = base.addingReportingOverflow(payload.partialValue)
    guard count >= 0, count <= maximumItemCount, !payload.overflow, !total.overflow else {
      throw ITunesDBError.badHeader("modern shuffle database is too large")
    }
    return total.partialValue
  }

  private static func checkedSum(_ values: Int...) throws -> Int {
    var result = 0
    for value in values {
      let addition = result.addingReportingOverflow(value)
      guard value >= 0, !addition.overflow else {
        throw ITunesDBError.badHeader("modern shuffle database is too large")
      }
      result = addition.partialValue
    }
    return result
  }

  private static func uint32(_ value: Int) throws -> UInt32 {
    guard let result = UInt32(exactly: value) else {
      throw ITunesDBError.badHeader("modern shuffle database is too large")
    }
    return result
  }

  private static func itemCount(_ value: UInt32, named name: String) throws -> Int {
    guard value <= UInt32(maximumItemCount) else {
      throw ITunesDBError.badHeader("implausible modern shuffle \(name) count \(value)")
    }
    return Int(value)
  }
}
